### ISSUE TITLE
Shutting down server with latest release causes an error

### ISSUE THREAD

**Issue by MineAnPlay** [ApacheTech-VintageStory-Mods/SteadyCam#1]
# 🐛 Bug Report

Shutting down the server with the /stop command causes an error and game crashes. This can be reproduced with only this mod and/or (Campaign Cartographer). 

## 💻 Screenshots / Stack Trace

Shutting down a server with /stop on the latest version of SteadyCam or Campaign Cartographer causes an error in the shutdown process. The server enters the shutdown process (thus I can't obtain logs), but because it encounters the error it also doesn't shutdown properly (does not write the save to file thus every time you restart the server it is rewinds to latest autosave). When the error is encountered the following is spammed an unknown amount of times (longer than default CMD history):
```
at ApacheTech.Common.DependencyInjection.ServiceProvider.Dispose()
   at Gantry.Core.Hosting.ModHost.DisposeOnLeaveWorld()
   at Gantry.Core.Hosting.ModHost.Dispose()
```
After this spam the following stack trace is found:
```
   at Vintagestory.Common.ModLoader.TryRunModPhase(Vintagestory.API.Common.Mod, Vintagestory.API.Common.ModSystem, Vintagestory.API.Common.ICoreAPI, Vintagestory.Common.ModRunPhase)
   at Vintagestory.Common.ModLoader.RunModPhase(System.Collections.Generic.List`1<Vintagestory.API.Common.ModSystem> ByRef, Vintagestory.Common.ModRunPhase)
   at Vintagestory.Common.ModLoader.RunModPhase(Vintagestory.Common.ModRunPhase)
   at Vintagestory.Common.ModLoader.Dispose()
   at Vintagestory.Server.ServerSystemModHandler.OnBeginShutdown()
   at Vintagestory.Server.ServerMain.EnterRunPhase(Vintagestory.API.Server.EnumServerRunPhase)
   at Vintagestory.Server.ServerMain.Stop(System.String)
   at Vintagestory.Server.CmdStop.handleStop(Vintagestory.API.Common.TextCommandCallingArgs)
   at Vintagestory.Common.ChatCommandImpl.CallHandler(Vintagestory.API.Common.TextCommandCallingArgs, System.Action`1<Vintagestory.API.Common.TextCommandResult>, System.Collections.Generic.Dictionary`2<Int32,Vintagestory.API.Common.AsyncParseResults>)
   at Vintagestory.Common.ChatCommandImpl.Execute(Vintagestory.API.Common.TextCommandCallingArgs, System.Action`1<Vintagestory.API.Common.TextCommandResult>)
   at Vintagestory.Common.ChatCommandApi.Execute(System.String, Vintagestory.API.Common.TextCommandCallingArgs, System.Action`1<Vintagestory.API.Common.TextCommandResult>)
   at Vintagestory.Server.ServerMain.ReceiveServerConsole(System.String)
   at Vintagestory.Server.ServerConsole+<>c__DisplayClass8_0.<readAsync>b__0()
   at Vintagestory.Server.ServerMain.ProcessMainThreadTasks()
   at Vintagestory.Server.ServerMain.ProcessMain()
   at Vintagestory.Server.ServerMain.Process()
   at Vintagestory.Server.ServerProgram.Main()
   at Vintagestory.ClientNative.CrashReporter.Start(System.Threading.ThreadStart)
   at Vintagestory.Server.ServerProgram..ctor()
   at Vintagestory.Server.ServerProgram.Main(System.String[])
   at VintagestoryServerLinux.ServerWindows.Main(System.String[])
```

## 🤔 Expected Behaviour

Proper and safe shutdown of server.

## 😯 Current Behaviour

Error occurs in the shutdown process, causing issues like not writing world to save file. Could be causing more issues that are unknown.

## 💁 Possible Solution

Latest version of both SteadyCam and Campaign Cartographer has this issue. Error seems to stem from Gantry which could be because of latest changes to code, wrong project used for compiling code, or something on my end (missing/outdated programs/libraries).

## 🔦 Context

Shutting down properly and safely. This can possibly be effecting more than just simple rewinds.

## 🌍 Log Files

No log files as the server initiated shutdown process and stopped logging. (Last line is "Entering runphase Shutdown" and no errors before this)

## 🌍 Your Environment

* OS & Device: Windows 11
* Game Version: v1.19.8
* Mods Version: v1.4.0

**Comment by ApacheTech** [comment]
Fixed for 1.4.1 of SteadyCam, and 4.0.1 of CampaignCartographer.
